services:
  handwritenrecognition.api:
    image: handwritenrecognition.api
    build:
      context: .
      dockerfile: HandwritenRecognition.API/Dockerfile

  hr.machinelearningapi:
    image: hr.machinelearningapi
    build:
      context: .
      dockerfile: Hr.MachineLearningAPI/Dockerfile
  
