// <auto-generated />
using System;
using HandwritenRecognition.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HandwritenRecognition.API.Migrations
{
    [DbContext(typeof(OcrDbContext))]
    [Migration("20260223185318_RulesNewColumns")]
    partial class RulesNewColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HandwritenRecognition.Data.Entities.FieldRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("ConfidenceWeight")
                        .HasColumnType("real");

                    b.Property<string>("DetectionPattern")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FieldType")
                        .HasMaxLength(300)
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<float>("MinConfidence")
                        .HasColumnType("real");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("Scope")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<bool>("UseNextLine")
                        .HasColumnType("bit");

                    b.Property<string>("ValidationPattern")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.HasKey("Id");

                    b.ToTable("FieldRules");
                });

            modelBuilder.Entity("HandwritenRecognition.Data.Entities.ImageInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ActualHeight")
                        .HasColumnType("int");

                    b.Property<int>("ActualWidth")
                        .HasColumnType("int");

                    b.Property<int>("OcrJobResultId")
                        .HasColumnType("int");

                    b.Property<int>("OriginalHeight")
                        .HasColumnType("int");

                    b.Property<int>("OriginalWidth")
                        .HasColumnType("int");

                    b.Property<Guid>("ResultId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ResultId");

                    b.ToTable("ImageInfos");
                });

            modelBuilder.Entity("HandwritenRecognition.Data.Entities.OcrDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("ConfidenceAvg")
                        .HasColumnType("real");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("HandwritenRecognition.Data.Entities.OcrJob", b =>
                {
                    b.Property<Guid>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Error")
                        .HasMaxLength(10000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid?>("ResultId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasMaxLength(60)
                        .HasColumnType("int");

                    b.HasKey("JobId");

                    b.HasIndex("ResultId");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("HandwritenRecognition.Data.Entities.OcrLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Confidence")
                        .HasColumnType("real");

                    b.Property<string>("CorrectedText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LineIndex")
                        .HasColumnType("int");

                    b.Property<Guid?>("OcrResultResultId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OriginalText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("OcrResultResultId");

                    b.ToTable("Lines");
                });

            modelBuilder.Entity("HandwritenRecognition.Data.Entities.OcrResult", b =>
                {
                    b.Property<Guid>("ResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ResultId");

                    b.ToTable("Results");
                });

            modelBuilder.Entity("HandwritenRecognition.Data.Entities.ProcessData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("OcrJobResultId")
                        .HasColumnType("int");

                    b.Property<int>("ProcessingTime")
                        .HasColumnType("int");

                    b.Property<string>("Profile")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid>("ResultId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ResultId");

                    b.ToTable("ProcessDatas");
                });

            modelBuilder.Entity("HandwritenRecognition.Data.Entities.QualityData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("BlurScore")
                        .HasColumnType("real");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<int>("OcrJobResultId")
                        .HasColumnType("int");

                    b.Property<Guid>("ResultId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ResultId");

                    b.ToTable("QualityDatas");
                });

            modelBuilder.Entity("HandwritenRecognition.Data.Entities.ImageInfo", b =>
                {
                    b.HasOne("HandwritenRecognition.Data.Entities.OcrResult", "Result")
                        .WithMany("ImageInfo")
                        .HasForeignKey("ResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Result");
                });

            modelBuilder.Entity("HandwritenRecognition.Data.Entities.OcrJob", b =>
                {
                    b.HasOne("HandwritenRecognition.Data.Entities.OcrResult", "Result")
                        .WithMany()
                        .HasForeignKey("ResultId");

                    b.Navigation("Result");
                });

            modelBuilder.Entity("HandwritenRecognition.Data.Entities.OcrLine", b =>
                {
                    b.HasOne("HandwritenRecognition.Data.Entities.OcrDocument", "Document")
                        .WithMany("Lines")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HandwritenRecognition.Data.Entities.OcrResult", null)
                        .WithMany("Lines")
                        .HasForeignKey("OcrResultResultId");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("HandwritenRecognition.Data.Entities.ProcessData", b =>
                {
                    b.HasOne("HandwritenRecognition.Data.Entities.OcrResult", "Result")
                        .WithMany("ProcessInfo")
                        .HasForeignKey("ResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Result");
                });

            modelBuilder.Entity("HandwritenRecognition.Data.Entities.QualityData", b =>
                {
                    b.HasOne("HandwritenRecognition.Data.Entities.OcrResult", "Result")
                        .WithMany("Quality")
                        .HasForeignKey("ResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Result");
                });

            modelBuilder.Entity("HandwritenRecognition.Data.Entities.OcrDocument", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("HandwritenRecognition.Data.Entities.OcrResult", b =>
                {
                    b.Navigation("ImageInfo");

                    b.Navigation("Lines");

                    b.Navigation("ProcessInfo");

                    b.Navigation("Quality");
                });
#pragma warning restore 612, 618
        }
    }
}
