// <auto-generated />
using System;
using HandwritenRecognition.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HandwritenRecognition.API.Migrations
{
    [DbContext(typeof(OcrDbContext))]
    [Migration("20260421075417_PreprocessedFilePathFix")]
    partial class PreprocessedFilePathFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HandwritenRecognition.Data.Entities.DocumentTypes", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DocumentTypes");
                });

            modelBuilder.Entity("HandwritenRecognition.Data.Entities.ExtractedFields", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Confidence")
                        .HasColumnType("real");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DocumentTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SourceOcrDocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("WasHumanCorrected")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DocumentTypeId");

                    b.HasIndex("RuleId");

                    b.HasIndex("SourceOcrDocumentId");

                    b.ToTable("ExtractedFields");
                });

            modelBuilder.Entity("HandwritenRecognition.Data.Entities.FieldRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float?>("ConfidenceWeight")
                        .HasColumnType("real");

                    b.Property<string>("DetectionPattern")
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<Guid>("DocumentTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FieldTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<float?>("MinConfidence")
                        .HasColumnType("real");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<Guid>("ScopeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("UseNextLine")
                        .HasColumnType("bit");

                    b.Property<string>("ValidationPattern")
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentTypeId");

                    b.HasIndex("FieldTypeId");

                    b.HasIndex("ScopeId");

                    b.HasIndex("TypeId");

                    b.ToTable("FieldRules");
                });

            modelBuilder.Entity("HandwritenRecognition.Data.Entities.FieldType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SrcDocumentTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SrcDocumentTypeId");

                    b.ToTable("FieldType");
                });

            modelBuilder.Entity("HandwritenRecognition.Data.Entities.ImageInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ActualHeight")
                        .HasColumnType("int");

                    b.Property<int>("ActualWidth")
                        .HasColumnType("int");

                    b.Property<int>("OcrJobResultId")
                        .HasColumnType("int");

                    b.Property<int>("OriginalHeight")
                        .HasColumnType("int");

                    b.Property<int>("OriginalWidth")
                        .HasColumnType("int");

                    b.Property<Guid>("ResultId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ResultId");

                    b.ToTable("ImageInfos");
                });

            modelBuilder.Entity("HandwritenRecognition.Data.Entities.OcrBoundingBox", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("H")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<Guid>("SourceLineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("W")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<int>("X")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<int>("Y")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SourceLineId");

                    b.ToTable("OcrBoundingBox");
                });

            modelBuilder.Entity("HandwritenRecognition.Data.Entities.OcrDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("ConfidenceAvg")
                        .HasColumnType("real");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("HandwritenRecognition.Data.Entities.OcrJob", b =>
                {
                    b.Property<Guid>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Error")
                        .HasMaxLength(10000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PreprocessedFileName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid?>("ResultId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasMaxLength(60)
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("JobId");

                    b.HasIndex("ResultId");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("HandwritenRecognition.Data.Entities.OcrLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BoundingBox")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Confidence")
                        .HasColumnType("real");

                    b.Property<string>("CorrectedText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LineIndex")
                        .HasColumnType("int");

                    b.Property<Guid?>("OcrResultResultId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OriginalText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("OcrResultResultId");

                    b.ToTable("Lines");
                });

            modelBuilder.Entity("HandwritenRecognition.Data.Entities.OcrResult", b =>
                {
                    b.Property<Guid>("ResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ResultId");

                    b.ToTable("Results");
                });

            modelBuilder.Entity("HandwritenRecognition.Data.Entities.ProcessData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("OcrJobResultId")
                        .HasColumnType("int");

                    b.Property<float>("ProcessingTime")
                        .HasColumnType("real");

                    b.Property<string>("Profile")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid>("ResultId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ResultId");

                    b.ToTable("ProcessDatas");
                });

            modelBuilder.Entity("HandwritenRecognition.Data.Entities.QualityData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("BlurScore")
                        .HasColumnType("real");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<int>("OcrJobResultId")
                        .HasColumnType("int");

                    b.Property<Guid>("ResultId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ResultId");

                    b.ToTable("QualityDatas");
                });

            modelBuilder.Entity("HandwritenRecognition.Data.Entities.RuleScope", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("RuleScope");
                });

            modelBuilder.Entity("HandwritenRecognition.Data.Entities.RuleType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("RuleType");
                });

            modelBuilder.Entity("HandwritenRecognition.Data.Entities.ExtractedFields", b =>
                {
                    b.HasOne("HandwritenRecognition.Data.Entities.DocumentTypes", "DocumentType")
                        .WithMany("ExtractedFieldsForDocument")
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HandwritenRecognition.Data.Entities.FieldRule", "Rule")
                        .WithMany("ExtractedFieldsList")
                        .HasForeignKey("RuleId");

                    b.HasOne("HandwritenRecognition.Data.Entities.OcrDocument", "SourceOcrDocument")
                        .WithMany("ExtractedFieldsForDocument")
                        .HasForeignKey("SourceOcrDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentType");

                    b.Navigation("Rule");

                    b.Navigation("SourceOcrDocument");
                });

            modelBuilder.Entity("HandwritenRecognition.Data.Entities.FieldRule", b =>
                {
                    b.HasOne("HandwritenRecognition.Data.Entities.DocumentTypes", "DocumentType")
                        .WithMany("RulesForDocType")
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HandwritenRecognition.Data.Entities.FieldType", "FieldType")
                        .WithMany("Rules")
                        .HasForeignKey("FieldTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HandwritenRecognition.Data.Entities.RuleScope", "Scope")
                        .WithMany("Rules")
                        .HasForeignKey("ScopeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HandwritenRecognition.Data.Entities.RuleType", "Type")
                        .WithMany("Rules")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentType");

                    b.Navigation("FieldType");

                    b.Navigation("Scope");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("HandwritenRecognition.Data.Entities.FieldType", b =>
                {
                    b.HasOne("HandwritenRecognition.Data.Entities.DocumentTypes", "SrcDocumentType")
                        .WithMany("FieldTypesForDoc")
                        .HasForeignKey("SrcDocumentTypeId");

                    b.Navigation("SrcDocumentType");
                });

            modelBuilder.Entity("HandwritenRecognition.Data.Entities.ImageInfo", b =>
                {
                    b.HasOne("HandwritenRecognition.Data.Entities.OcrResult", "Result")
                        .WithMany("ImageInfo")
                        .HasForeignKey("ResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Result");
                });

            modelBuilder.Entity("HandwritenRecognition.Data.Entities.OcrBoundingBox", b =>
                {
                    b.HasOne("HandwritenRecognition.Data.Entities.OcrLine", "SourceLine")
                        .WithMany("BoundingBoxes")
                        .HasForeignKey("SourceLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceLine");
                });

            modelBuilder.Entity("HandwritenRecognition.Data.Entities.OcrJob", b =>
                {
                    b.HasOne("HandwritenRecognition.Data.Entities.OcrResult", "Result")
                        .WithMany()
                        .HasForeignKey("ResultId");

                    b.Navigation("Result");
                });

            modelBuilder.Entity("HandwritenRecognition.Data.Entities.OcrLine", b =>
                {
                    b.HasOne("HandwritenRecognition.Data.Entities.OcrDocument", "Document")
                        .WithMany("Lines")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HandwritenRecognition.Data.Entities.OcrResult", null)
                        .WithMany("Lines")
                        .HasForeignKey("OcrResultResultId");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("HandwritenRecognition.Data.Entities.ProcessData", b =>
                {
                    b.HasOne("HandwritenRecognition.Data.Entities.OcrResult", "Result")
                        .WithMany("ProcessInfo")
                        .HasForeignKey("ResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Result");
                });

            modelBuilder.Entity("HandwritenRecognition.Data.Entities.QualityData", b =>
                {
                    b.HasOne("HandwritenRecognition.Data.Entities.OcrResult", "Result")
                        .WithMany("Quality")
                        .HasForeignKey("ResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Result");
                });

            modelBuilder.Entity("HandwritenRecognition.Data.Entities.DocumentTypes", b =>
                {
                    b.Navigation("ExtractedFieldsForDocument");

                    b.Navigation("FieldTypesForDoc");

                    b.Navigation("RulesForDocType");
                });

            modelBuilder.Entity("HandwritenRecognition.Data.Entities.FieldRule", b =>
                {
                    b.Navigation("ExtractedFieldsList");
                });

            modelBuilder.Entity("HandwritenRecognition.Data.Entities.FieldType", b =>
                {
                    b.Navigation("Rules");
                });

            modelBuilder.Entity("HandwritenRecognition.Data.Entities.OcrDocument", b =>
                {
                    b.Navigation("ExtractedFieldsForDocument");

                    b.Navigation("Lines");
                });

            modelBuilder.Entity("HandwritenRecognition.Data.Entities.OcrLine", b =>
                {
                    b.Navigation("BoundingBoxes");
                });

            modelBuilder.Entity("HandwritenRecognition.Data.Entities.OcrResult", b =>
                {
                    b.Navigation("ImageInfo");

                    b.Navigation("Lines");

                    b.Navigation("ProcessInfo");

                    b.Navigation("Quality");
                });

            modelBuilder.Entity("HandwritenRecognition.Data.Entities.RuleScope", b =>
                {
                    b.Navigation("Rules");
                });

            modelBuilder.Entity("HandwritenRecognition.Data.Entities.RuleType", b =>
                {
                    b.Navigation("Rules");
                });
#pragma warning restore 612, 618
        }
    }
}
